// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXbYasd2jBkrIJE8xmZdlOBOjRQ4RQN2w',
    appId: '1:569397411478:web:48ff714937bd4754d80cb7',
    messagingSenderId: '569397411478',
    projectId: 'flutter-mobile-webrtc',
    authDomain: 'flutter-mobile-webrtc.firebaseapp.com',
    storageBucket: 'flutter-mobile-webrtc.appspot.com',
    measurementId: 'G-4DB7GPFPF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcbihoxhxucIUjbpou47FT5Z9MWh3Src',
    appId: '1:569397411478:android:279b7bdc32c2224ed80cb7',
    messagingSenderId: '569397411478',
    projectId: 'flutter-mobile-webrtc',
    storageBucket: 'flutter-mobile-webrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYIb-m8pxLmFzyEPjFALB7ivyGt_tklc',
    appId: '1:569397411478:ios:bce2d1e21bf1bf3dd80cb7',
    messagingSenderId: '569397411478',
    projectId: 'flutter-mobile-webrtc',
    storageBucket: 'flutter-mobile-webrtc.appspot.com',
    iosBundleId: 'com.example.flutterWebrtcDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnYIb-m8pxLmFzyEPjFALB7ivyGt_tklc',
    appId: '1:569397411478:ios:bce2d1e21bf1bf3dd80cb7',
    messagingSenderId: '569397411478',
    projectId: 'flutter-mobile-webrtc',
    storageBucket: 'flutter-mobile-webrtc.appspot.com',
    iosBundleId: 'com.example.flutterWebrtcDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXbYasd2jBkrIJE8xmZdlOBOjRQ4RQN2w',
    appId: '1:569397411478:web:bc6974710e1d5dffd80cb7',
    messagingSenderId: '569397411478',
    projectId: 'flutter-mobile-webrtc',
    authDomain: 'flutter-mobile-webrtc.firebaseapp.com',
    storageBucket: 'flutter-mobile-webrtc.appspot.com',
    measurementId: 'G-YQM8ZPWYSK',
  );
}
